

# ose official node runtime as parent image
FROM node:20

# set the working directory in the container
WORKDIR /usr/src/app

# copy the current directory conents into the container at the aformentioned directory
COPY . . 

# install the packages in package.json
RUN npm install

# make port at 3000 open to the outside world
EXPOSE 3000

# run the launch code when the container launches
CMD ["node", "app.js"]